import { authenticated } from "../../middlewares/authenticated";
import { authorizeRoles } from "../../middlewares/authorized";
import AuthRoute from "./auth";
import UsersAdmin from "./users";
import voteRoute from "./votes";
import { Router } from "express";
const route = Router();
route.use("/auth", AuthRoute);
route.use(authenticated, authorizeRoles("admin"));
route.use("/users", UsersAdmin);
route.use("/votes", voteRoute);
export default route;
