import { authenticated } from "../../middlewares/authenticated";
import { authorizeRoles } from "../../middlewares/authorized";
import PostsRoute from "./posts";
import CompetitionRoute from "./competitions";
import ComplaintRoute from "./complaints";
import ComplaintsCategoryRoute from "./complaintsCategory";
import AuthRoute from "./auth";
import UsersAdmin from "./users";
import voteRoute from "./votes";
import { Router } from "express";
const route = Router();
route.use("/auth", AuthRoute);
route.use(authenticated, authorizeRoles("admin"));
route.use("/users", UsersAdmin);
route.use("/votes", voteRoute);
route.use("/posts", PostsRoute);
route.use("/complaints/category", ComplaintsCategoryRoute);
route.use("/complaints", ComplaintRoute);
route.use("/competitions", CompetitionRoute);
export default route;
