import { authenticated } from "../../middlewares/authenticated";
import { authorizeRoles } from "../../middlewares/authorized";
import AuthRoute from "./auth";
import ComplaintsRoute from "./complaints";
import { Router } from "express";
const route = Router();
route.use("/auth", AuthRoute);
route.use(authenticated, authorizeRoles("approved_user"));
route.use("/complaints", ComplaintsRoute);
export default route;
